### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by pangirl** [sherpadawan/orfeomm.com#12]
Il faudrait ajouter un module(?) oû les personnes intéressées puissent s'abonnerà notre nesletter

**Comment by pangirl** [comment]
Bonjour Pour la gestion des abonnés je pense que ça serait bien qu'il y ait les deux inscriptions: sur le site et aussi dans le BO par l'administrateur ou la personne responsable de la news letter.
Celle-ci devrait être un contenu spécifique.
CA a validé les besoins exprimés par la commission concernant la mise en place de la newsletter et l’ajout de deux rubriques ( sous forme de texte ) au menu d’accueil (échanges internationaux et prestations artistiques).
 si tu veux on peut te renconter pour se mettre d'accord sur nos souhaits et ce qu'on peut faire pour y répondre.

**Comment by sherpadawan** [comment]
En ligne
