### ISSUE TITLE
Rubrique dans page d.accueil

### ISSUE THREAD

**Issue by pangirl** [sherpadawan/orfeomm.com#17]
Nous voudrions rajouter dans le menu de la page d.accueil : prestations proposées (concert à vendre)et une autre rubrique  "échanges internationaux " ( liens album photos).
Le contenu de ces deux rubriques étant présenté sous forme de texte.

**Comment by sherpadawan** [comment]
Si je comprends bien il s'agit d'ajouter des éléments dans le menu principal ! De la même façon que evènement ?
Est-il réellement nécessaire de faire une page échanges internationaux qui présente uniquement du texte et un lien vers votre galerie photo ? Ou c'est qqch qui pourrait se mettre ailleurs. Je pose simplement la question ?

**Comment by sherpadawan** [comment]
La rubrique prestation est en ligne,
les échanges internationaux en attente voir #20
