### ISSUE TITLE
Carrousel page d.accueil

### ISSUE THREAD

**Issue by pangirl** [sherpadawan/orfeomm.com#18]
Nous aimerions savoir les dimensions des photos que l'on peut mettre pour qu.elles ne soient pas coupées quand elles défilent.

**Comment by sherpadawan** [comment]
largeur = 828px 
hauteur =  285px

**Comment by sherpadawan** [comment]
Il est possible d'obtenir cette information en cliquant droit sur l'image -> voir l'image -> propriétés
