### ISSUE TITLE
newsletter

### ISSUE THREAD

**Issue by pangirl** [sherpadawan/orfeomm.com#19]
existe-t-il un module pour envoyer notre newsletter?

**Comment by sherpadawan** [comment]
Pour le moment aucun module n'est installé, cette fonctionnalité n'était pas prévu au départ.
Il faudrait me faire une expression de besoin synthétique, avec la liste des fonctionnalités attendues.
Ensuite je trouverai la solution la plus adapté à votre besoin.

Gestion des contacts dans le back office ?
Formulaire d'inscription sur le site ? Ou inscription dans le BO par l'administrateur ?
Publication de quelles informations ? Est-ce qu'on considère que les évènements actuels sont des newsletter ou voulez vous un contenu spécifique au format html et ou pdf par exemple ?

**Comment by pangirl** [comment]
Bonjour Pour la gestion des abonnés je pense que ça serait bien qu'il y ait les deux inscriptions: sur le site et aussi dans le BO par l'administrateur ou la personne responsable de la news letter.
Celle-ci devrait être un contenu spécifique.
CA a validé les besoins exprimés par la commission concernant la mise en place de la newsletter et l’ajout de deux rubriques ( sous forme de texte ) au menu d’accueil (échanges internationaux et prestations artistiques).
 si tu veux on peut te renconter pour se mettre d'accord sur nos souhaits et ce qu'on peut faire pour y répondre.

**Comment by pangirl** [comment]
Bonjour Pour la gestion des abonnés je pense que ça serait bien qu'il y ait les deux inscriptions: sur le site et aussi dans le BO par l'administrateur ou la personne responsable de la news letter.
Celle-ci devrait être un contenu spécifique.
CA a validé les besoins exprimés par la commission concernant la mise en place de la newsletter et l’ajout de deux rubriques ( sous forme de texte ) au menu d’accueil (échanges internationaux et prestations artistiques).
 si tu veux on peut te renconter pour se mettre d'accord sur nos souhaits et ce qu'on peut faire pour y répondre.

**Comment by sherpadawan** [comment]
Bonjour,

Ok bonne nouvelle! Je pense qu'il serait bien que vous produisiez un document simple avec le détail de votre besoin, cela vous aidera à le clarifier.
Je crée 2 demandes différentes porur les rubriques souhaitées

**Comment by sherpadawan** [comment]
Ok on ferme cette demande et on continue de discuter de ca dans #12
